#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Start the server on 8081 by default so it won't conflict with other local apps
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/user_service
spring.datasource.username=app_user
spring.datasource.password=Casper
spring.jpa.hibernate.ddl-auto=update

# Use the MySQL dialect when connecting to MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Google OAuth2 (set env vars in your shell)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
# Start Google login at: /oauth2/authorization/google
#Ashish Maurya